import turtle
t=turtle.Turtle()
l=int(input("Enter the length of the Rectangle:"))
w=int(input("Enter the width of the Rectangle:"))
t.forward(l)
t.left(90)
t.forward(w)
t.left(90)
t.forward(l)
t.left(90)
t.forward(w)
t.left(90)
turtle.color("red")
